[package]
name = "krust_kernel"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
#compiler_builtins = { features = ["mem"] }
